if: tag IS present OR type = api

env:
  global:
    - CIBW_ARCHS=aarch64
    - CIBW_SKIP=pp38-*

language: python
# Default Python version is usually 3.6
python: "3.12"
dist: jammy
services: docker

jobs:
  include:
    - name: "manylinux2014 aarch64"
      os: linux
      arch: arm64
      env:
        - CIBW_BUILD="*manylinux*"
        - CIBW_MANYLINUX_AARCH64_IMAGE=manylinux2014
        - CIBW_MANYLINUX_PYPY_AARCH64_IMAGE=manylinux2014
    - name: "manylinux_2_28 aarch64"
      os: linux
      arch: arm64
      env:
        - CIBW_BUILD="*manylinux*"
        - CIBW_MANYLINUX_AARCH64_IMAGE=manylinux_2_28
        - CIBW_MANYLINUX_PYPY_AARCH64_IMAGE=manylinux_2_28
    - name: "musllinux aarch64"
      os: linux
      arch: arm64
      env:
        - CIBW_BUILD="*musllinux*"

install:
    - python3 -m pip install -r .ci/requirements-cibw.txt

script:
    - python3 -m cibuildwheel --output-dir wheelhouse
    - ls -l "${TRAVIS_BUILD_DIR}/wheelhouse/"

# Upload wheels to GitHub Releases
deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/wheelhouse/*.whl"
  on:
    repo: python-pillow/Pillow
    tags: true
  skip_cleanup: true
